//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.NewHireOnboarding.LoadTests
{
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestTools.WebTesting;

    public class FeedBackWebTestCoded : WebTest
    {

        public FeedBackWebTestCoded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            WebTestRequest request1 = new WebTestRequest(TestConstants.ViewFeedbackRequestUrl);
            request1.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            yield return request1;
            request1 = null;
        }
    }
}
